# Generated by Django 5.0.6 on 2024-05-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meals_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
