# Generated by Django 5.0.6 on 2024-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meals_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meals', 'verbose_name_plural': 'meals'},
        ),
    ]
