# Generated by Django 5.0.6 on 2024-05-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
