# Generated by Django 5.0.6 on 2024-06-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='people',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='preperation_time',
        ),
    ]
