# Generated by Django 5.0.6 on 2024-09-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_meals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
