# Generated by Django 5.0.6 on 2025-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_meals_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.TextField(),
        ),
    ]
